[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["C.J.Kent <cjkent@hotmail.com>"]

[dependencies]
log = "0.3.5"
env_logger = "0.3.2"
time = "0.1.34"
bmp = "0.1.4"
threadpool = "0.2.1"
#simd = { git = "https://github.com/huonw/simd" }
